@echo off
set /p r="Enter RED value of RGB shift from wallpaper color (value can be negative): "
set /p g="Enter GREEN value of RGB shift from wallpaper color (value can be negative): "
set /p b="Enter BLUE value of RGB shift from wallpaper color (value can be negative): "
set /p x="Enter X value of clock position relative to the top right corner of the screen: "
set /p y="Enter Y value of clock position relative to the top right corner of the screen: "
set /p font="Enter font name: "
set /p size="Enter font size (number): "
set /p weight="Enter font weight (string, ex. bold): "
set /p inv="Inverse RGB values for better contrast? (1 for yes, 0 for no): "
echo COLOR_SHIFT = (%r%, %g%, %b%) > "%appdata%\Microsoft\Windows\Start Menu\Programs\Startup\custom.py"
echo POSITION = (%x%, %y%) >> "%appdata%\Microsoft\Windows\Start Menu\Programs\Startup\custom.py"
echo FONT = ("%font%", %size%, "%weight%") >> "%appdata%\Microsoft\Windows\Start Menu\Programs\Startup\custom.py"
echo INVERSE = %inv% >> "%appdata%\Microsoft\Windows\Start Menu\Programs\Startup\custom.py"
