@echo off
set /p name="Enter your theme's name: "
set /p r="Enter RED value of RGB shift from wallpaper color (value can be negative): "
set /p g="Enter GREEN value of RGB shift from wallpaper color (value can be negative): "
set /p b="Enter BLUE value of RGB shift from wallpaper color (value can be negative): "
set /p x="Enter X value of clock position relative to the top right corner of the screen: "
set /p y="Enter Y value of clock position relative to the top right corner of the screen: "
set /p font="Enter font name: "
set /p size="Enter font size (number): "
set /p weight="Enter font weight (string, ex. bold): "
echo COLOR_SHIFT = (%r%, %g%, %b%) > "%appdata%\Microsoft\Windows\Start Menu\Programs\Startup\custom.py"
echo POSITION = (%x%, %y%) >> "%appdata%\Microsoft\Windows\Start Menu\Programs\Startup\custom.py"
echo FONT = ("%font%", %size%, "%weight%") >> "%appdata%\Microsoft\Windows\Start Menu\Programs\Startup\custom.py"
echo COLOR_SHIFT = (%r%, %g%, %b%) ^> "%appdata%\Microsoft\Windows\Start Menu\Programs\Startup\custom.py" > "themes\%name%.bat"
echo POSITION = (%x%, %y%) ^>^> "%appdata%\Microsoft\Windows\Start Menu\Programs\Startup\custom.py" >> "themes\%name%.bat"
echo FONT = ("%font%", %size%, "%weight%") ^>^> "%appdata%\Microsoft\Windows\Start Menu\Programs\Startup\custom.py" >> "themes\%name%.bat"
